name: Lint
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
